### ISSUE TITLE
Package Naming Restrictions

### ISSUE THREAD

**Issue by cdw3** [android-js/androidjs#103]
When uploading an APK to Google Play, I receive the following failure message:

> You need to use a different package name because "com.android" is restricted.

I do not use "com.android" in any of my specifications.  I did not find a way to remove that in the androidjs documentation.  Will there be a feature for that in the future?

**Comment by Chhekur** [comment]
We'll fix this issue in next release for sure

Feel free to ask in case of any problem ; )

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)

**Comment by Chhekur** [comment]
@cdw3 this issue has been fixed, just update the `androidjs-builder` to latest version
run the following command to do so
```sh
$ npm install -g androidjs-builder@2.1.8
```

Feel free to ask in case of any problem ; )
