### ISSUE TITLE
Cannot post on store after signed

### ISSUE THREAD

**Issue by Romans96** [android-js/androidjs#108]
Hello! I've signed the app with keystore and ubser sign, but when i try to put the app in Play Console it returns 2 errors:
1. Debugabble app active;
2. Package with com.android....;

The 1 i modified the manifest.xml in .androidjs in android:debuggable="false", but it doesn't help.
For the second i already saw a post of 5 days ago about this bug.

Thank you

**Comment by Chhekur** [comment]
Hey @Romans96,
1. we have updated our `SDK` to fix the 1<sup>st</sup> issue.
2. we have updated the `androidjs-builder` to fix 2<sup>nd</sup> issue.

So you just need to update the `SDK` and `androidjs-builder` then you'll good to go ; )
Here's the commands for doing so
```sh
$ npm install -g androidjs-builder@2.1.6
$ androidjs update
```

Feel free to ask in can of any problem ; )

**Comment by Romans96** [comment]
> Hey @Romans96,
> 
> 1. we have updated our `SDK` to fix the 1st issue.
> 2. we have updated the `androidjs-builder` to fix 2nd issue.
> 
> So you just need to update the `SDK` and `androidjs-builder` then you'll good to go ; )
> Here's the commands for doing so
> 
> ```shell
> $ npm install -g androidjs-builder@2.1.6
> $ androidjs update
> ```
> 
> Feel free to ask in can of any problem ; )


Just tried after updated both, signed with uber apk signer, and it works and it is signed. Tried to putting it on play console. It returns the error for debuggable app activated. (for package it does not returns any error.
In the .androidjs sdk the androidmanifest i have debug="false";

**Comment by Romans96** [comment]
<i tried both, removing android:debug from android-sdk in the androidmanifest, or also puttting it asfalse, but nothing

**Comment by Chhekur** [comment]
We are trying to solve this issue and let you know once done ; )

**Comment by Romans96** [comment]
> We are trying to solve this issue and let you know once done ; )

Hello! It works now?

Best regards

**Comment by Chhekur** [comment]
Not yet give us some more time : )

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)

**Comment by Chhekur** [comment]
@Romans96  we have updated `androidjs-builder`  and `SDK`  for release  mode
here’s all the instructions, how you can generate release build
1. upgrade your `androidjs-builder` to latest version
```sh
$ npm install androidjs-builder@2.1.8
```
 2.  update the SDK to latest version
```sh
androidjs update
```
 3.  run build  command with --release  flag
```sh
androidjs build --release
```
4.  resign the apk with your own private keystore

Documentation is also updated for all these, refer to the docs here

Feel free to ask in case of any problem ; )
