### ISSUE TITLE
Admob feature in apk

### ISSUE THREAD

**Issue by hardx4** [android-js/androidjs#109]
Correct me if I'm wrong, but from the little I read in the builder's source code, I have a slight impression that the webview apk that is created, seems to be a rebuild of another APK.  If so, could you provide an apk to rebuild with admob SDK?  so that we can edit the manifest with the publisher’s data?  Sorry me if i'm wrong.

**Comment by Chhekur** [comment]
Yeah, right now there is no API for Admob but we are planning to implement it very soon.

Feel free to ask in case of any problem ; )
