### ISSUE TITLE
Remove app name from top

### ISSUE THREAD

**Issue by AnteraTres** [android-js/androidjs#110]
Any app that i make without the "fullScreen" mode on the Theme option always have this bar where the appname is in. ¿Is it possible to remove it? I want the users to be able to see the hour or if they have other notifications while using my apps.

![WhatsApp Image 2020-04-14 at 13 10 52](https://user-images.githubusercontent.com/4683551/79218823-629b0a00-7e51-11ea-974e-5c7e5f53b440.jpeg)

Thank you!

**Comment by Chhekur** [comment]
Are you using the latest version of `androidjs-builder` ?

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)

**Comment by Chhekur** [comment]
@AnteraTres we have fixed this please download the latest version of `androidjs-builder@2.1.7`.

In order to download latest version, run the following command
```sh
$ npm install -g androidjs-builder@2.1.7
```

Feel free to ask in case of any problem ; )
