### ISSUE TITLE
Screen Orientation 

### ISSUE THREAD

**Issue by adamrpostjr** [android-js/androidjs#111]
Is there a way to lock screen orientation?

Do you have an official discord or telegram?
Do you have a way to donate for the efforts

**Comment by Chhekur** [comment]
We'll implement it ASAP ; )

Yes, we have created a slack channel for `Android JS` community, you can join here https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ

Yes, we have added `Sponsor` link as well to the repository.

Feel free to ask in case of any problem ; )

**Comment by Chhekur** [comment]
@adamrpostjr  we have implemented this please download the latest version of `androidjs-builder@2.1.7`.

In order to download latest version, run the following command
```sh
$ npm install -g androidjs-builder@2.1.7
```

Feel free to ask in case of any problem ; )
