### ISSUE TITLE
androidjs-sdk is being download, everytime I build the project 

### ISSUE THREAD

**Issue by shaikh-amaan-fm** [android-js/androidjs#117]
Everytime I build the project using "androidjs b -f" command, androidjs-sdk starts getting download everytime.
Shouldn't this happen only once and not everytime? 

![image](https://user-images.githubusercontent.com/53618794/82915971-0ae2d900-9f8f-11ea-894b-fa721c7388b0.png)

**Comment by Chhekur** [comment]
You should use `androidjs b` instead of force command
Because force download all the assets to make build process as new every time.

Feel free to ask in case of any problem ; )

**Comment by shaikh-amaan-fm** [comment]
> You should use `androidjs b` instead of force command
> Because force download all the assets to make build process as new every time.
> 
> Feel free to ask in case of any problem ; )

Thanks for your quick response, your solution did worked for me! : )
