### ISSUE TITLE
can not find package.json

### ISSUE THREAD

**Issue by x770** [android-js/androidjs#118]
I tried to run it today for the first time, and i only added permissions to the app nothing more, and when i try to build i get 

\AndroidTest> androidjs build --force 
can not find package.json

How can it not see the package.json file when i only just wrote multiple permissions in it ? please help me !

**Comment by x770** [comment]
i fixed it

**Comment by NeevJewalkar** [comment]
how did you fix the issue?

**Comment by Chhekur** [comment]
> how did you fix the issue?

Try running the command from projects root folder.
