### ISSUE TITLE
Where to keep any custom config files used by node js code

### ISSUE THREAD

**Issue by oHarishR** [android-js/androidjs#120]
I wanted to keep some json files which is used by the main.js. 
Tried to keep those files under views folder and tried under same directory of main.js but it does not pick up.

**Comment by Chhekur** [comment]
It shouldn't happen you can keep those files along with your mail.js
there might be some exception, you can check logcat for more info. why it doesn't pick up

**Comment by oHarishR** [comment]
I kept vss.json file in the same directory where main.js file is there but somehow it does not pickup.

07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): Irregular format of VSS json. Exit1.Error: ENOENT: no such file or directory, open './vss.json'
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Object.openSync (fs.js:436:3)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Object.readFileSync (fs.js:341:35)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Object.<anonymous> (/data/data/com.androidjs.viss/files/myapp/main.js:93:25)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Module._compile (internal/modules/cjs/loader.js:688:30)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Module.load (internal/modules/cjs/loader.js:598:32)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
07-16 08:43:38.932 I/NODEJS-MOBILE( 9465):     at Function.Module.runMain (internal/modules/cjs/loader.

**Comment by Chhekur** [comment]
> I kept vss.json file in the same directory where main.js file is there but somehow it does not pickup.
> 
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): Irregular format of VSS json. Exit1.Error: ENOENT: no such file or directory, open './vss.json'
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Object.openSync (fs.js:436:3)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Object.readFileSync (fs.js:341:35)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Object. (/data/data/com.androidjs.viss/files/myapp/main.js:93:25)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Module._compile (internal/modules/cjs/loader.js:688:30)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Module.load (internal/modules/cjs/loader.js:598:32)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Function.Module._load (internal/modules/cjs/loader.js:529:3)
> 07-16 08:43:38.932 I/NODEJS-MOBILE( 9465): at Function.Module.runMain (internal/modules/cjs/loader.

instead of json, I would recommend to use JS files and directly import them instead of regular file operations.

**Comment by oHarishR** [comment]
okay, I resolved the issue using require statements for the available json file.
Thanks.
