### ISSUE TITLE
API level error when releasing on Play Store

### ISSUE THREAD

**Issue by Software-City** [android-js/androidjs#134]
**Describe the bug**
When I try to upload my App on Play Store I get this Error:
"Your app currently targets API level 28 and must target at least API level 29 to ensure that it is built on the latest APIs optimised for security and performance. Change your app's target API level to at least 29."

I have successfully signed the app, so that's not the problem.

**To Reproduce**
1. Create an App and sign it in release mode
2. Create new release to Play Store App
3. Upload the .apk file

**Expected behavior**
Upload without any errors

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Browser Chrome
 - Version latest

**Comment by nmagko** [comment]
That is a reminder to upgrade to API Level 29. You can continue publishing your release though. Starting november 2, 2020, updates to apps on Google Play will be required to target API level 29 or higher.

**Comment by Chhekur** [comment]
Hey Guys, thanks for pointing this out, we have upgraded our AndroidJS SDK to support Android API level upto 30.
so please just go ahead and update your SDK and enjoy ; )
here'r the instructions to update SDK 
https://android-js.github.io/docs/installation.html#update-sdk
```sh
$ androidjs update
```

join out slack community too, for faster responses.
[Slack Channel](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ) for support and discussion

**Comment by nmagko** [comment]
Hi, it works like a charm. Thanks.

If you are using _jarsigner_ you have to change to _apksigner_ to sign your APP for API Level 30.

apksigner sign --ks path_to/<app>.keystore <app>.apk
