### ISSUE TITLE
How to access app object from main.js so I can use app.getPath in main.js

### ISSUE THREAD

**Issue by ajuga2** [android-js/androidjs#135]
how can i access app object main.js so I can use app.getPath in main.js

**Comment by Chhekur** [comment]
You can't access `app` in `main.js`.

What you can do is access the `app.getPath` function in views and send the value using `IPC` to `main.js`.

**Comment by ajuga2** [comment]
Ok. thanks. Very satisfied by the way. I ported my nodejs application from windows to android. Also works in BlueStacks
