### ISSUE TITLE
Slack channel no longer works + some questions

### ISSUE THREAD

**Issue by inf3rno** [android-js/androidjs#152]
I have a few questions, and the slack channel does not seem to work.
I am curious which android versions are supported and if I can run background process or services with Android JS? I want to do polling in every 10 mins via HTTP instead of using FCM if possible.

**Comment by Chhekur** [comment]
Hey, can you elaborate what is the problem you are facing with slack?
it supports Android API level up to 30, and sorry to say but right now there is nothing live background service in Android JS, we are working on it but it someone can contribute to this that will be great and making us ship features fasters

**Comment by inf3rno** [comment]
![swdfcrgvhn](https://user-images.githubusercontent.com/408911/100457912-2c9a5580-30c3-11eb-8d02-6b74735ff708.png)

**Comment by inf3rno** [comment]
> 
> 
> Hey, can you elaborate what is the problem you are facing with slack?
> it supports Android API level up to 30, and sorry to say but right now there is nothing live background service in Android JS, we are working on it but it someone can contribute to this that will be great and making us ship features fasters

Okay, thanks.

**Comment by Chhekur** [comment]
@inf3rno can you check with this link https://androidjs.slack.com, does it work for you?

**Comment by inf3rno** [comment]
@Chhekur  Yes, thanks!
