### ISSUE TITLE
Does it support SPA?

### ISSUE THREAD

**Issue by murunwas** [android-js/androidjs#17]
does this framework support Single Page Application such as React or Vue?

**Comment by Chhekur** [comment]
Yes it support both Single Page Application and Multi Page Application as well.

If you have any doubts feel free to write us!

Thanks!

**Comment by murunwas** [comment]
I have tried to use vue but it is giving me blank screen, can you please add an example using SPA?

**Comment by Chhekur** [comment]
you can do it in this way:-
create a server in `main.js` file start it on some port other that 3000.
then in `index.html` redirect it to your server like app.loadURL('http://localhost:4000');
something like this then you will have your server working in webview at front and a server at the back.

**Comment by Chhekur** [comment]
I'll provide you a better approach soon.

**Comment by Chhekur** [comment]
This is the `Hello World Example of Vue JS` build on `Android JS`
[https://github.com/android-js/sample-app/tree/master/vue-js-example](https://github.com/android-js/sample-app/tree/master/vue-js-example)

no need to create server at all this is very simple example just by using html and vue js

if you have any doubts, feel free to write us !

Thanks!

**Comment by Chhekur** [comment]
for debugging first run your app in browser.
open `index.html` file in `browser` and run `main.js` file using `node`

**Comment by murunwas** [comment]
thank you sir, let me test it now

**Comment by murunwas** [comment]
when building the app, it always copy the phonon  boilerplate app even thou i'm not using it and it increase the bundle size

**Comment by Chhekur** [comment]
Did you generate the project with `androidjs b`

**Comment by Chhekur** [comment]
If you are generating project like this, it will generate the sample phonon app

You should generate project with scratch 
Try this: [https://blog.usejournal.com/how-to-build-android-apps-with-node-js-using-android-js-2aa4643be87b](https://blog.usejournal.com/how-to-build-android-apps-with-node-js-using-android-js-2aa4643be87b)

**Comment by murunwas** [comment]
I generated it from scratch but when I run `androidjs build` in the `/dist/app-debug/assets` folder, I always found that boilerplate even thou I don't have it in my `views` folder

**Comment by murunwas** [comment]
![image](https://user-images.githubusercontent.com/8838943/56468246-c864d980-6429-11e9-9a4b-cdcd70e9a83c.png)

**Comment by Chhekur** [comment]
Update the `androidjs-builder` to the latest version and delete the `dist` folder and build again

**Comment by DeveshPankaj** [comment]
You can generate scratch app via ``androidjs g --example helloworld``

**Comment by murunwas** [comment]
I updated the `androidjs-builder` and now I'm getting this error

![image](https://user-images.githubusercontent.com/8838943/56468518-eb918800-642d-11e9-87b0-055cfa31582a.png)

**Comment by android-js** [comment]
User force command
 ``androidjs b -f``

**Comment by murunwas** [comment]
the `main.js` when I install the apk on my device.

**Comment by murunwas** [comment]
The `main.js` does not run when I install the apk on my device.

**Comment by Chhekur** [comment]
How do you come to know `main.js` does not run.

**Comment by murunwas** [comment]
because when I try to invoke the functions in the `main.js` there's no response

**Comment by Chhekur** [comment]
Did you used IPC for making communication between `Back Process` and `Front Process`.

**Comment by murunwas** [comment]
I followed that, on development it is working fine but when I build and install apk on my device, there's no response from the server / `main.js`

**Comment by Chhekur** [comment]
could you please share the code of `index.html` and `main.js` file ?

**Comment by murunwas** [comment]
`main.js`

![image](https://user-images.githubusercontent.com/8838943/56469725-a8d7ac00-643d-11e9-8141-7a66b3d49805.png)

`app.js`

![image](https://user-images.githubusercontent.com/8838943/56469749-ef2d0b00-643d-11e9-9ede-bce6c575b0ed.png)

`index.html`

![image](https://user-images.githubusercontent.com/8838943/56469759-11bf2400-643e-11e9-8c38-cf3721ccf3b1.png)

**Comment by Chhekur** [comment]
we fixed some bugs and sorry to say that 

- you have to update `androidjs-builder` to the latest one again
- and `androidjs.js` file as well because your are using older one new: [android.js](https://github.com/android-js/androidjs/blob/master/lib/androidjs.js)

and you have to update your `app.js` file something like this:

```js
new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!',
    number:"",
    list: []
  },
  methods:{
  	call(){
  		app.call.makeCall(this.number)
  	},
  	server(){
  		front.send('Hello', this.number);
  	}
  },
  mounted(){
  	front.on('print', function(msg){
           // because this.list says undefined
  	    this.list = this.list || [];
  	    this.list.push(msg)
  	    let node = document.createElement('LI');
  	    node.appendChild(document.createTextNode(msg));
  	    document.getElementById('numbers').appendChild(node);
  	    console.log(list);
  	})
  }
})
```

and `index.html`

```html
<!DOCTYPE html>
<html>
<head>
	<title>Vue Example</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>

<style>
	.app{
		font-size:30px;
	}
</style>

<body>
<div id="app" class = "app">
	{{ message }}
	<input type = "text" v-model = "number" /> <br />
	<button @click="call">call</button>
	<button @click="server">server</button>
	<hr/>
	<ul id = "numbers">
		<li v-for="(a,i) in list":key="i">{{a}}</li>
	</ul>
</div>
</body>
<script type="text/javascript" src = "../assets/androidjs.js"></script>
<script type="text/javascript" src = "../assets/app.js"></script>
</html>
```

and `package.json` like this because in order to use `Call API` you need to add `android.permission.CALL_PHONE` permission to your `package.json` file

```json
{
  "name": "vue_example",
  "app-name": "Vue Example",
  "package-name": "mypkg",
  "icon": "./assets/icon/icon.png",
  "dist-path": "./dist",
  "permission": [
    "android.permission.INTERNET",
    "android.permission.CALL_PHONE"
  ],
  "version": "1.0.0",
  "description": "",
  "main": "script.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "androidjs": "^1.0.5"
  }
}
```

**Comment by murunwas** [comment]
thank you, I'll give it a try...

**Comment by murunwas** [comment]
on `main`  as shown below, can I name the script whatever I want or it is suppose to be `main.js` or `script.js`?

![image](https://user-images.githubusercontent.com/8838943/56473497-58c40e00-646c-11e9-984d-e0d9a2dfc70d.png)

**Comment by Chhekur** [comment]
It doesn't matter 😉

**Comment by murunwas** [comment]
lols it matters cause if I named it `main.js` it works fine but if i named it `script.js` my app crashes 😉😉😉

**Comment by Chhekur** [comment]
> lols it matters cause if I named it `main.js` it works fine but if i named it `script.js` my app crashes

I think that because of something else, may be
