### ISSUE TITLE
What's the difference between WebView and Static?

### ISSUE THREAD

**Issue by daydreamercodes** [android-js/androidjs#174]
I know what WebView is but there are WebView and Static preferences when creating a new project. I'm a little bit confused. Can someone explain the difference?
Edit: I got it

**Comment by Johnny-John-John** [comment]
hmm now could you tell us what it was?

**Comment by Chhekur** [comment]
@Johnny-John-John in static project there is no `node` run time environment, this is the only different b/w WebView and Static.

**Comment by Johnny-John-John** [comment]
ah thats nice, thanks for explaining it to me
