### ISSUE TITLE
Transition between pages

### ISSUE THREAD

**Issue by FilippoPaganelli** [android-js/androidjs#180]
First, amazing project. Second, is there a way to simulate a nice transition between pages similar to a real Android app? For instance, a slide transition from a main div to another content.

**Comment by DeveshPankaj** [comment]
Check out this awesome framework for making mobile responsive design [Phonon](https://phonon.quarkdev.com), [Onsen](https://onsen.io/demo)

Hope this can help you building your next awesome app.             happy coding  XD
