### ISSUE TITLE
Using this framework with express, Vuejs vue-router and vuex

### ISSUE THREAD

**Issue by realrecordzLab** [android-js/androidjs#186]
I want to give a try to this library to use nodejs for mobile andorid applications. I'm usually using vuejs and bootstrap for the front-end. I've seen the example on how to generate an app and the SPA provided example but it's not clear a thing. 
Is possible to use a vuejs project generated using vue ui or vue cli that will include vuex and vue router with this framework?

If is possible, I suppose that I need to add the js library to the index and all the assets after the vue app is build, inside the css and js folders inside assets?

Is also possible to use express and serve the vue app from the server?

**Comment by DeveshPankaj** [comment]
Both ways are possible to build an app using AndroidJS
- You can use Vue CLI to create and build the app. in this case you will need to place the build files in [`views`](https://android-js.github.io/docs/generating_project.html) folder and build the app.
- Changing the build directory also can help. 
- Using Express server can also be an option to serve (`redirect to server IP from views/index.html`).

**Comment by realrecordzLab** [comment]
> Both ways are possible to build an app using AndroidJS
>
> * You can use Vue CLI to create and build the app. in this case you will need to place the build files in [`views`](https://android-js.github.io/docs/generating_project.html) folder and build the app.

The problem is that vue CLI during the build will create separate folders for js/css and assets and the builded app that is loaded from `index.html` file will look for this files inside the same folder where the index reseide. Form the documentations of this library I see that the it will have an assets folder where all the js css and other app resources needs to be placed. How the vue build process can be configured to place the css/js files inside the assets folder of androidjs project? 

> * Changing the build directory also can help.
What do you mean with changing the build directory?

> * Using Express server can also be an option to serve (`redirect to server IP from views/index.html`).

My idea is to use a localhost express serverthat will run inside the app and that will serve the vue app, this to avoid the problem to move the vue builded app files into the different folders used from the library
