### ISSUE TITLE
Generated apk not loading vue app

### ISSUE THREAD

**Issue by realrecordzLab** [android-js/androidjs#190]
I've followed the instrudction on how to setup a simple project. I've installed globally `androidjs-builder` and after I've created a folder for my project I've run the `androidjs init` command that have created a folder with the needed structure for the project. I want to use vue for the app but to generate the project I'm using vue CLI, I have a separated folder where I'm creating the front-end of the app. After the build process of the vue app is done, I've builded the android app using `androidjs build --release` command. The apk is generated correctly but when I install it into android emulator I will get a blank screen ando not see the default hello word component created by vue CLI. 

I've configured vue to save the build css/js files inside the assets folder of the project created from androidjs, this is the `vue.config.js` file:
```js
module.exports = {
    assetsDir: '../../demoapp/assets/',
    indexPath: '../../demoapp/views/index.html',
    productionSourceMap: false
}
```

Since I want to use single file components and vue CLI, is there any way to make the things working as expected?

**Comment by Chhekur** [comment]
Hey @realrecordzLab,
what you need to do is move your `index.html` file in the `views` directory, then it should work.

**Comment by realrecordzLab** [comment]
> Hey @realrecordzLab,
> what you need to do is move your `index.html` file in the `views` directory, then it should work.

Already did it. The problem was with the vue assets files linking, I have edited manually the generated `index.html` and replaced the linking of the files with the correct path that is `assets` where I'm placing the css and js folders of the vue app.

**Comment by realrecordzLab** [comment]
For everyone that will have the same problme here are the steps to follow if you are using vue cli to create the front-end of your mobile app: 

1) Create a new project with vue cli
2) Build the vue app
3) Edit the generated `index.html` file to include `androidjs.js` library and to correct the vue app scripts links and place it inside the `views` directory
4) Place the vue generated `css` and `js` folders into the `assets` directory of androidjs project
5) Build your android app

**Comment by Chhekur** [comment]
@realrecordzLab you can actually use webpack to automate the whole process like adding `androidjs.js` to your `index.html` and placing generated css and js files to a specific location.

**Comment by realrecordzLab** [comment]
> @realrecordzLab you can actually use webpack to automate the whole process like adding `androidjs.js` to your `index.html` and placing generated css and js files to a specific location.

adding androidjs to the index is simple and can be done without webpack, it's only necessary to add the androidjs libray script tag to the header of the `index.html` file in the public folder of the vue project before build the app. Vue cli will copy that index file and the final build will include androidjs library. 

For webpack, I never used it so I don'k know how to proceed for moving folders. Thanks for the suggestion
