### ISSUE TITLE
dist folder doesn't generate

### ISSUE THREAD

**Issue by itsthrask** [android-js/androidjs#198]
**Describe the bug**
At the terminal it shows that the apk is generated but there is no sign of the dist folder 

 - OS: kali linux

**Comment by DeveshPankaj** [comment]
Hi @itsthrask, can I know for which type of app you are facing this issue, are you trying to build a static app or NodeJS app?

**Comment by itsthrask** [comment]
@DeveshPankaj Yeah it is a NodeJS app

**Comment by DeveshPankaj** [comment]
- You can try changing the [`dist-path`](https://android-js.github.io/docs/configuring_app.html#adding-output-directory) in package.json
- If that doesn't work, you can get the apk from `~/.androidjs/cache`

**Comment by itsthrask** [comment]
@DeveshPankaj  Thank you, I found it
