### ISSUE TITLE
Problem with the certificate for google play

### ISSUE THREAD

**Issue by NikitaZZZ** [android-js/androidjs#202]
Good day. Please tell me how to sign an apk (aab) file with your own certificate in order to make a release on Google Play. We use Android js in our project.
Is there such a possibility in this framework?

**Comment by Chhekur** [comment]
Hey @NikitaZZZ ,
You can manually resign the apk generated by AndroidJS with your google certificate.
Right now there no possibility in AndroidJS to automatically sign with your google certificate.

**Comment by NikitaZZZ** [comment]
Is the apk file signed by default and can I create an aab file using androidjs?

**Comment by Chhekur** [comment]
> Is the apk file signed by default and can I create an aab file using androidjs? 

Yes the apk file is signed with default key, so you have to resign it with your google play certificate.
And right now we haven't provided any way to generate aab AFAIK.

**Comment by NikitaZZZ** [comment]
Thanks for answers
