### ISSUE TITLE
non zero exit code: failed to build apk

### ISSUE THREAD

**Issue by EiskalterFreund** [android-js/androidjs#206]
**Describe the bug**
I wanted to build my app, but then it just showed this 
```
non zero exit code: failed to build apk
W: fakeLogOpen(/dev/log_stats) failed
Unable to rename temporary file
``` 
and this was only 15 minutes after using it, first it worked fine, now it doesn't at all

**To Reproduce**
Idk how to reproduce, it happend randomly

**Expected behavior**
It should build my apk, what it didn't

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 11 latest
 - Browser Microsoft Edge Beta
 - Version Latest

**Additional context**
It didn't build my app and I am very mad because i need to code an project i am working on... And i don't want to waste all of my time fixing this crap...

**Comment by EiskalterFreund** [comment]
Please fix this as fast as possible!

**Comment by EiskalterFreund** [comment]
Or atleast add more debugging information so we can fix it ourselfs...

**Comment by EiskalterFreund** [comment]
Soo, if you delete the folder "C:/Users/%USERNAME%/.androidjs" then it works again!

**Comment by Chhekur** [comment]
@EiskalterFreund hey these permission generally comes on windows machine not sure, you might haven't given the proper permissions for that folder.

We actually use `.androidjs` folder as cache for our tool, so basically you won't have to download the SDK again and again.

**Comment by RizwanKMW** [comment]
Run this command it will rebuild it successfully
`$ androidjs build -f`

**Comment by fox3000foxy** [comment]
![image](https://github.com/android-js/androidjs/assets/40730498/459f29ad-9dfe-43a2-b57d-663a135eb1a0)

**Comment by fox3000foxy** [comment]
What should i do now ?
