### ISSUE TITLE
Is there any way to decompile apk generated by android js

### ISSUE THREAD

**Issue by kentang2017** [android-js/androidjs#209]
I have formated my computer and the original project sources have gone, only the apk left on my phone. Is there any way to decompile it into a project like the original one? Thanks

**Comment by DeveshPankaj** [comment]
@kentang2017 you can use [ApkTool](https://ibotpeaches.github.io/Apktool/) to recover your JavaScript files from apk

**Comment by kentang2017** [comment]
got it and thanks!

**Comment by psindra** [comment]
Open/Extract it with any zip viewer.
Under the folder "assets/{your_app_name}" you'll find your NodeJs project
