### ISSUE TITLE
non zero exit code while building apk

### ISSUE THREAD

**Issue by zerealone** [android-js/androidjs#255]
**Describe the bug**
When I'm trying to build the apk, there is a "non zero exit code" error

**To Reproduce**
1. I created an app with only single html file (all the other files like package.json are also there, but only single index.html in the views folder)
2. I wanted to build the app
3. I ran the command `androidjs build` in the shell.
4. I got an error : 
```
non zero exit code: failed to build apk
W: fakeLogOpen(/dev/log_stats) failed
W: C:\Users\my pc user\.androidjs\cache\sdk-static\res\values\styles.xml:13: error: Resource entry Animation.Design.BottomSheetDialog already has bag item android:windowNoTitle.
W: C:\Users\my pc user\.androidjs\cache\sdk-static\res\values\styles.xml:12: Originally defined here.
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\my pc user\AppData\Local\Temp\brut_util_Jar_14475138607310379111.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 30, --version-code, 1000032, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\my pc user\AppData\Local\Temp\APKTOOL1497937955621151830.tmp, -e, C:\Users\my pc user\AppData\Local\Temp\APKTOOL15820611983958087903.tmp, -0, arsc, -I, C:\Users\User\.androidjs\cache\1.apk, -S, C:\Users\my pc user\.androidjs\cache\sdk-static\res, -M, C:\Users\User\.androidjs\cache\sdk-static\AndroidManifest.xml]
```
My package.json file is same as in the docs, without any theme or something.

**Expected behavior**
I expect to get the .apk file in the /dist folder, which didn't happend.

**Screenshots**
I added the error above, so no screenshots needed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: No browser used
 If it's helping, I'm using Visual Studio Code
 
**Additional context**
I will thank you if you can fix it sometime soon. I really want to create an app with this amazing tool.

**Comment by emartisoft** [comment]
try it
`androidjs build -f`

**Comment by zerealone** [comment]
I tried already this,and it worked, but it result without the app logo, so it's not helpful.

**Comment by emartisoft** [comment]
> I tried already this,and it worked, but it result without the app logo, so it's not helpful.

Change/Edit png files in **/assets/icon** folder for your app logo (icon)

**Comment by zerealone** [comment]
I just copied the index.html file and pasted in a new project. Now it's working.
