### ISSUE TITLE
CORS Error when using Fetch in JS.

### ISSUE THREAD

**Issue by ftk789** [android-js/androidjs#268]
**Describe the bug**
When using `Fetch`, It gives CORS error in Chrome on PC, Now fixing it would be running Chrome with no flag and CORS disabled,
**To Reproduce**
1. Use fetch

**Expected behavior**
Fetch a local file.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Android

**Additional context**
When using Fetch, it gives CORS problem, Keep in mind I'm Fetching a local file like " Test.txt", Now when building the app, I have no clue how to allow the apk to Fetch the local file, Because i'm sure in the background it gives the CORS error as well, So yea.

**Comment by Zebraslive** [comment]
I have the same issue. This is the only thing preventing me from continuing to build my app.

In order to fix this someone would need to implement an api to disable CORS on the android.js webview.

something like app.disableCORS(true);

but i doubt they will add this ability anytime soon.

**Comment by ftk789** [comment]
@Zebraslive , Apparently, It's fixable by using fetch with this:
`  fetch("Something",{`
`    origin:'*', `
`  })`
