### ISSUE TITLE
[Suggestion] Add Android App Links

### ISSUE THREAD

**Issue by dan-online** [android-js/androidjs#33]
As seen here: https://developer.android.com/training/app-links

This would then open a dialog when the user goes to a certain website to ask whether they would like to open it in the app

**Comment by Chhekur** [comment]
We'll do that ASAP,
Thanks for your suggestions ; )

**Comment by dan-online** [comment]
Alright great thanks!

**Comment by Chhekur** [comment]
This functionality is already provided by android itself from Android M

**Comment by dan-online** [comment]
So how would I use this in androidjs?

**Comment by Chhekur** [comment]
> So how would I use this in androidjs?

What you actually want?
Do you want to list your app into when a link will be clicked or something else?

**Comment by dan-online** [comment]
Yes, when someone say clicks a link to go to example.com it would ask whether they want to open example.com in my app.

**Comment by Chhekur** [comment]
> Yes, when someone say clicks a link to go to example.com it would ask whether they want to open example.com in my app.

Okay, So you want android deep app linking

**Comment by dan-online** [comment]
Oh sorry! Yes

**Comment by Chhekur** [comment]
> Oh sorry! Yes

Hey,
`Deep Link API` is available in latest version of androidjs@2.0.1
and new version of androidjs-builder@2.0.0 is also available that support all the latest features.

check out docs for `Deep Link API` : https://android-js.github.io/androidjs/deeplink_api.html

we want you to use all the latest features and let us know if you find any kinda bug or error

Thanks ; )

**Comment by dan-online** [comment]
Hey! Thanks for this! I tried this in my app and app.deeplink.getLink() returned cannot read getLink() of undefined and app.deeplink is equal to an empty object: ``{}``.

**Comment by dan-online** [comment]
Also, when I attempt to build with the new androidjs-builder I get the error: ``Not a androidjs project``

**Comment by dan-online** [comment]
> Also, when I attempt to build with the new androidjs-builder I get the error: `Not a androidjs project`

I fixed this with adding ``"project-type": "webview",`` to my package.json but now the new error is that 
```js
if ('number' != typeof options.total) throw new Error('total required');
                                      ^
Error: total required
```

**Comment by Chhekur** [comment]
> > Also, when I attempt to build with the new androidjs-builder I get the error: `Not a androidjs project`
> 
> I fixed this with adding `"project-type": "webview",` to my package.json but now the new error is that
> 
> ```js
> if ('number' != typeof options.total) throw new Error('total required');
>                                       ^
> Error: total required
> ```

Can you please attach full screenshot of error ?

**Comment by dan-online** [comment]
![Screen Shot 2019-07-09 at 10 41 52 am](https://user-images.githubusercontent.com/41877062/60873204-3f925880-a236-11e9-98bb-e84a22b9c3b4.png)

**Comment by Chhekur** [comment]
Try the same command one more time 😅

**Comment by dan-online** [comment]
Oh yea works now lol. I will comment again once finished if the deep linking worked.

**Comment by dan-online** [comment]
Heres a new error:
```js
copying Assets
copying from /Users/me/Desktop/Code/Github-Web/Android 
to: /Users/me/.androidjs/androidjs-sdk/assets/myapp
[ '/Users/me/Desktop/Code/Github-Web/Android/dist' ]
(node:78664) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/Users/me/Desktop/Code/Github-Web/Android/node_modules/.bin/console-png'
```

**Comment by Chhekur** [comment]
> Heres a new error:
> 
> ```js
> copying Assets
> copying from /Users/me/Desktop/Code/Github-Web/Android 
> to: /Users/me/.androidjs/androidjs-sdk/assets/myapp
> [ '/Users/me/Desktop/Code/Github-Web/Android/dist' ]
> (node:78664) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/Users/me/Desktop/Code/Github-Web/Android/node_modules/.bin/console-png'
> ```

Post the full screenshot of error that will help us to debug

**Comment by Chhekur** [comment]
And package.json as well

**Comment by dan-online** [comment]
Here you go:
```js
building
checking Core
using core /Users/me/.androidjs/androidjs-sdk
removing /Users/me/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /Users/me/Desktop/Code/Github-Web/Android 
to: /Users/me/.androidjs/androidjs-sdk/assets/myapp
[ '/Users/me/Desktop/Code/Github-Web/Android/dist' ]
(node:78917) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/Users/me/Desktop/Code/Github-Web/Android/node_modules/.bin/console-png'
    at Object.readdirSync (fs.js:790:3)
    at listDirectorySync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:68:18)
    at copydirSync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:43:7)
    at copyFromArraySync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:75:3)
    at listDirectorySync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:69:3)
    at copydirSync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:43:7)
    at copyFromArraySync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:75:3)
    at listDirectorySync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:69:3)
    at copydirSync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:43:7)
    at copyFromArraySync (/usr/local/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:75:3)
(node:78917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:78917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
㋛ using androidjs-sdk {"version":"2.0.0"}
```
and the package.json:
```json
{
  "name": "GitApp",
  "version": "3.0.4",
  "description": "Android version of GitApp",
  "main": "main.js",
  "app-name": "GitApp",
  "package-name": "GitApp",
  "project-type": "webview",
  "icon": "./assets/icon.png",
  "permission": [
    "android.permission.INTERNET",
    "android.permission.WRITE_EXTERNAL_STORAGE"
  ],
  "dist-path": "./dist",
  "scripts": {
    "package": "androidjs b -f",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/dan-online/GitApp.git"
  },
  "author": "dan-online",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/dan-online/GitApp/issues"
  },
  "deep-link": [
    {
      "scheme": "http",
      "host": "github.com"
    },
    {
      "scheme": "https",
      "host": "github.com"
    },
    {
      "scheme": "http",
      "host": "github.co.uk"
    },
    {
      "scheme": "https",
      "host": "github.co.uk"
    }
  ],
  "homepage": "https://github.com/dan-online/GitApp#readme",
  "dependencies": {
    "androidjs": "^2.0.1"
  }
}

```

**Comment by dan-online** [comment]
Oh ok so I reinstalled androidjs-builder completely in my system and that seemed to work.

**Comment by dan-online** [comment]
Again I will mention when its finished and ive checked deep linking, thank you so much though!

**Comment by dan-online** [comment]
Works great! Thank you so much for your help.
