### ISSUE TITLE
[Suggestion] Add SMS func.

### ISSUE THREAD

**Issue by cxxus** [android-js/androidjs#34]
Hi,
I dont know - but i looked and did not see. Is there any possibility to send SMS without user acceptation?

Or if dont - it will be sooo useful, add it please :)

**Comment by Chhekur** [comment]
We'll implement the SMS API ASAP
Thanks for your suggestion ; )

**Comment by Chhekur** [comment]
Hey, we have implemented `SMS API` for `Android JS`.
So you can use it in your app to send `SMS`

You can take a look of same app as well : https://github.com/android-js/sample-app/tree/master/sms-app

Docs: https://android-js.github.io/docs/sms_api.html
