### ISSUE TITLE
[Suggestion] What about contacts API

### ISSUE THREAD

**Issue by appsdevpk** [android-js/androidjs#35]
When it will be available (contacts api)

**Comment by Chhekur** [comment]
It'll be available in next two days ; )

**Comment by appsdevpk** [comment]
Thanks bro, i am really enjoying working on androidjs.

**Comment by appsdevpk** [comment]
i think i will not be able to use this feature as ver 1.0.7 have some packaging issues as discussed here.
https://github.com/android-js/androidjs/issues/28

**Comment by Chhekur** [comment]
> i think i will not be able to use this feature as ver 1.0.7 have some packaging issues as discussed here.
> #28

We are gonna release new builder as well ; )

**Comment by Chhekur** [comment]
Hey,
`Contact API` is available in latest version of `androidjs@2.0.1`
and new version of `androidjs-builder@2.0.0` is also available that support all the latest features.

we want you to use all the latest features and let us know if you find any kinda bug or error

Thanks ; )
