### ISSUE TITLE
new builder not generating any project

### ISSUE THREAD

**Issue by appsdevpk** [android-js/androidjs#42]
**Describe the bug**
i just unistalled the old version and installed the latest one. when i tried to generate the project with the command androidjs g, it does nothing and outputs g in console.

**To Reproduce**
1. uninstall old versions of builder
2. install the latest one
3. try to generate the project with the command androidjs g

**Expected behavior**
Should generate a sample project

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Chhekur** [comment]
Command for package generation has been changes to `androidjs init`

Check out the documentation ; )

**Comment by appsdevpk** [comment]
OK, i got it, i tried it but got the error below when packaging.
![image](https://user-images.githubusercontent.com/516860/60804147-423d7100-a196-11e9-8c9e-946bfc9ba175.png)

**Comment by Chhekur** [comment]
> OK, i got it, i tried it but got the error below when packaging.
> ![image](https://user-images.githubusercontent.com/516860/60804147-423d7100-a196-11e9-8c9e-946bfc9ba175.png)

We are trying to fix this issue,

Can you please try `androidjs update` command and let us know what happene

**Comment by appsdevpk** [comment]
here is the output.
![image](https://user-images.githubusercontent.com/516860/60805159-c264d600-a198-11e9-94ff-d0b6a34ca9ce.png)

**Comment by Chhekur** [comment]
> here is the output.
> ![image](https://user-images.githubusercontent.com/516860/60805159-c264d600-a198-11e9-94ff-d0b6a34ca9ce.png)

we are fixing the issues and thanks for bug report ; )

**Comment by Chhekur** [comment]
Update your builder to latest version `androidjs-builder@2.0.1`
And enjoy ; )

**Comment by appsdevpk** [comment]
here is the next issue after updating to the latest version, same error when packaging
![image](https://user-images.githubusercontent.com/516860/60871788-e4b82b80-a24c-11e9-88ea-d2f3d236cbbe.png)

**Comment by Chhekur** [comment]
Manually create directory with same name, right now

**Comment by appsdevpk** [comment]
i did it but still got the same error, you can see of left side that the directory exists.
![image](https://user-images.githubusercontent.com/516860/60874754-f2bc7b00-a251-11e9-8af7-bac81ce68311.png)

**Comment by Chhekur** [comment]
We are not getting this error any how.
Try to reinstall `androidjs-builder` and use adminstrator mode CMD

**Comment by appsdevpk** [comment]
still getting the same error in administrator mode

**Comment by Chhekur** [comment]
> still getting the same error in administrator mode

Try it on cmd not power shell because no other user face this issue

**Comment by appsdevpk** [comment]
![image](https://user-images.githubusercontent.com/516860/60881172-8d22bb80-a25e-11e9-9bc0-50e09c77aead.png)

**Comment by Chhekur** [comment]
Wait I got the bug

**Comment by Chhekur** [comment]
Are you using latest version 2.0.1?
And did you install it as global package ?

**Comment by appsdevpk** [comment]
yes for both

**Comment by Chhekur** [comment]
Follow following instructions in order to make it work
1. uninstall already existing `androidjs-builder`
2. delete `.androidjs` folder from your `users\<username>\.androidjs` directory
3. install latest version of `androidjs-builder@2.0.2`

then you will good to go ; )
let me know if you face any kinda bug again !

**Comment by appsdevpk** [comment]
the first error when initializing the project
![image](https://user-images.githubusercontent.com/516860/60910957-80708880-a29b-11e9-9bca-b51f22e36bbd.png)
the second one when packaging
![image](https://user-images.githubusercontent.com/516860/60910988-90886800-a29b-11e9-9e94-26e4dd047a36.png)

**Comment by Chhekur** [comment]
> the first error when initializing the project
> ![image](https://user-images.githubusercontent.com/516860/60910957-80708880-a29b-11e9-9bca-b51f22e36bbd.png)
> the second one when packaging
> ![image](https://user-images.githubusercontent.com/516860/60910988-90886800-a29b-11e9-9e94-26e4dd047a36.png)

First error is just issue with directory write permission, you can ignore that

In order to solve second error try to run build command again, it will gone

**Comment by Chhekur** [comment]
Let me know, if it works

**Comment by appsdevpk** [comment]
![image](https://user-images.githubusercontent.com/516860/60911895-a26b0a80-a29d-11e9-8026-88f40e89bacb.png)

**Comment by Chhekur** [comment]
Internet connection is required !
Repeatedly try the same command because some time it works and some time not.

We are trying to figure out that issue

**Comment by Chhekur** [comment]
Or if you want to make it work right now, you can do this downloding step manually.
Download https://github.com/android-js/androidjs-sdk as zip and then extract it in `users\<username>\.androidjs\androidjs-sdk`

Then try building command

**Comment by appsdevpk** [comment]
it worked after 4 tries

**Comment by appsdevpk** [comment]
thanks a lot for such a wonderful lib, it will save a lot of time in my future projects

**Comment by Chhekur** [comment]
> thanks a lot for such a wonderful lib, it will save a lot of time in my future projects

Once you done with your app you can actually post your app on `androidjs` app showcase.
We would love to showcase apps that are built using `androidjs` ; )
