### ISSUE TITLE
Changing app id

### ISSUE THREAD

**Issue by appsdevpk** [android-js/androidjs#43]
**Is your feature request related to a problem? Please describe.**
How can i change my app id like com.company.appname

**Describe the solution you'd like**
Able to change app id from package.json

**Comment by appsdevpk** [comment]
Also i have developed some apps in cordova and want to rewrite those in android js, any help here?

**Comment by Chhekur** [comment]
> **Is your feature request related to a problem? Please describe.**
> How can i change my app id like com.company.appname
> 
> **Describe the solution you'd like**
> Able to change app id from package.json

It is already there check out the documentation
https://android-js.github.io/androidjs/configuring_app.html#change-the-package-name-of-your-app

We ask about the `package name` in `package.json` to make app id something like this : `com.android.js. <your package name>`
