### ISSUE TITLE
No contacts or wifi object

### ISSUE THREAD

**Issue by appsdevpk** [android-js/androidjs#47]
**Describe the bug**
The wifi, contacts and a lot of other objects are not defined in app object

**To Reproduce**
debug the app using weinre, just take a look at the screenshot

**Screenshots**
![androidjs_debugg](https://user-images.githubusercontent.com/516860/63887780-f8834100-c9f6-11e9-8137-a701576ecf69.png)

**Desktop:**
 - OS: Windows 10
 - Browser chrome
 - Version 76

**Smartphone:**
 - Device: Nexus 6P
 - OS: 8.1

**Comment by appsdevpk** [comment]
is anyone here?

**Comment by Chhekur** [comment]
> is anyone here?

I think you are not using the latest version of `Android JS`
Download latest from [here](https://github.com/android-js/androidjs/blob/master/build/lib/androidjs.js)
