### ISSUE TITLE
Blue notification bar

### ISSUE THREAD

**Issue by EthanHermsey** [android-js/androidjs#49]
Hey @Chhekur!

Nice project, it's a very easy and nice way to make android apps. I don't really have a bug but a question. 
I got a test app to work just fine, however the notification bar of my phone colors blue. Is there a way to change that color? 

here's a screenshot: https://imgur.com/PrJKbwV

Thanks in advance.
Ethan.

**Comment by Chhekur** [comment]
Hi @EthanHermsey,
Right now there is no way to do that so I am  adding it my features list then it'll be available in next update ;)

**Comment by EthanHermsey** [comment]
That would be so nice :) Could the app maybe be fullscreen without the bar?

**Comment by Chhekur** [comment]
> That would be so nice :) Could the app maybe be fullscreen without the bar?

This feature has been implemented in the newest version of `androidjs-builder@2.0.3`.
check out the documentation for more info [here](https://android-js.github.io/docs/change_theme.html)

**Comment by EthanHermsey** [comment]
Aahw yes! :D You did it, that's awesome :)
I'm going to check it out this week. 
Very cool man! thnx
