### ISSUE TITLE
Remove StatusBar

### ISSUE THREAD

**Issue by szhatef** [android-js/androidjs#50]
I would like to remove StatusBar, like what we can do with this Theme: 
@android:style/Theme.NoTitleBar.Fullscreen

Best Regards

**Comment by Chhekur** [comment]
We'll put it in next update for sure ; )

**Comment by szhatef** [comment]
> We'll put it in next update for sure ; )

And do you have any estimation for release time of that? (BTW how stupid question it could be :)) )

**Comment by Chhekur** [comment]
> > We'll put it in next update for sure ; )
> 
> And do you have any estimation for release time of that? (BTW how stupid question it could be :)) )

most probably by tomorrow ; )

**Comment by Chhekur** [comment]
This feature has been implemented in the newest version of `androidjs-builder@2.0.3`.
check out the documentation for more info [here](https://android-js.github.io/docs/change_theme.html)
