### ISSUE TITLE
Add the possibility to edit WebView settings from package.json

### ISSUE THREAD

**Issue by zRattly** [android-js/androidjs#53]
**Is your feature request related to a problem? Please describe.**
I need to start a worker file but WebView blocks it from Same-Origin policy but you can unlock it using a setting.

**Describe the solution you'd like**
A section in package.json like :
`"webview-settings": {"sample-setting": true}`

**Describe alternatives you've considered**
None

**Additional context**
https://stackoverflow.com/questions/32020039/using-a-web-worker-in-a-local-file-webview

**Comment by Chhekur** [comment]
Could you please elaborate, what you actually want ?

**Comment by zRattly** [comment]
I need to use a [Worker](https://developer.mozilla.org/it/docs/Web/API/Worker) for an encrypted chat with socket.io and OpenPGP(which requires the worker), but, Chrome and all chrome-related browsers uses the Same-Origin policy that blocks these workers, but, you can disable it by using a [flag](chrome://flags).

By digging more I found out [this](https://stackoverflow.com/questions/32020039/using-a-web-worker-in-a-local-file-webview) StackOverflow question that shows how to fix this, so i'd like to have a package.json section for webview settings.

**Comment by zRattly** [comment]
I've tryed to explain this in the best way possible.

**Comment by Chhekur** [comment]
> I need to use a [Worker](https://developer.mozilla.org/it/docs/Web/API/Worker) for an encrypted chat with socket.io and OpenPGP(which requires the worker), but, Chrome and all chrome-related browsers uses the Same-Origin policy that blocks these workers, but, you can disable it by using a flag.
> 
> By digging more I found out [this](https://stackoverflow.com/questions/32020039/using-a-web-worker-in-a-local-file-webview) StackOverflow question that shows how to fix this, so i'd like to have a package.json section for webview settings.

This is already set to true, you can check to the source [here](https://github.com/android-js/android-native-apis/blob/master/androidjs/src/main/java/com/android/js/webview/AndroidJSActivity.java)

**Comment by zRattly** [comment]
oh lmao
sorry for wasting your time lmao
