### ISSUE TITLE
write on files inside assets Folder

### ISSUE THREAD

**Issue by szhatef** [android-js/androidjs#54]
I want to run a code (included in main.js (back) ) in order to write on a file which is located inside the "assets" Folder by using:
> fs.writeFileSync ( **filePath** , newData , 'utf8' );  

but I can not do that ( either the path is not correct or I am dealing with a permission issue ).

How can I do that? what would be the  **filePath** ?

(in PC it works Fine, but in Android that code makes crash)

**Comment by Chhekur** [comment]
You can not write files that are inside the `assets` folder because at the run time these files are no more in `assets`.

You can read/write files in users directory
Check [here](https://android-js.github.io/docs/app.html)

**Comment by szhatef** [comment]
> You can not write files that are inside the `assets` folder because at the run time these files are no more in `assets`.
> 
> You can read/write files in users directory
> Check [here](https://android-js.github.io/docs/app.html)

thank for the answer 
but how can I defiene "app" ? I used this but wont helpo:
> const app = require ( 'androidjs' ).app;

**Comment by Chhekur** [comment]
> > You can not write files that are inside the `assets` folder because at the run time these files are no more in `assets`.
> > You can read/write files in users directory
> > Check [here](https://android-js.github.io/docs/app.html)
> 
> thanks for the answer
> but how can I defiene "app" ? I used this but wont help:
> 
> > const app = require ( 'androidjs' ).app;

`app` module is given in front process

**Comment by szhatef** [comment]
> > > You can not write files that are inside the `assets` folder because at the run time these files are no more in `assets`.
> > > You can read/write files in users directory
> > > Check [here](https://android-js.github.io/docs/app.html)
> > 
> > 
> > thanks for the answer
> > but how can I defiene "app" ? I used this but wont help:
> > > const app = require ( 'androidjs' ).app;
> 
> `app` module is given in front process

but I need to deal with it in back process, is there any chance to get the '**userData**' Folder  path in order to write on it in Back process?

**Comment by Chhekur** [comment]
> > `app` module is given in front process
> 
> but I need to deal with it in back process, is there any chance to get the '**userData**' Folder's Path, in order to write on it, in Back process?

You can use `IPC` to share information between `front` and `back` process.

**Comment by szhatef** [comment]
> You can use `IPC` to share information between `front` and `back` process.

I used that but in Mobile it immediately closes:

`    // ------- send App Location to back
    let path = app.getPath('userData');
    front.send ( 'here' , path );`

`back.on ( 'here'     , function (data) { const here = data;  } );
answer = Object.assign ( {} , answer_template );
    answer[ 'stat' ] = 'looking_in';
    
    directories = fs.readdirSync ( here );
    answer[ 'retrieved_data' ] = directories;
    back.send`

**Comment by Chhekur** [comment]
> > You can use `IPC` to share information between `front` and `back` process.
> 
> I used that but in Mobile it immediately closes:
> 
> > // ------- send App Location to back
> > let path = app.getPath('userData');
> > front.send ( 'here' , path );
> 
> > back.on ( 'here'     , function (data) { const here = data;  } );
> > answer = Object.assign ( {} , answer_template );
> > answer[ 'stat' ] = 'looking_in';
> > directories = fs.readdirSync ( here );
> > answer[ 'retrieved_data' ] = directories;
> > back.send ( 'Hey_you' , answer );

You have to read read operations inside the callback function because javascript is async or you can use promise

**Comment by szhatef** [comment]
> You have to read read operations inside the callback function because javascript is async or you can use promise

   > answer = Object.assign ( {} , answer_template );
   > answer[ 'stat' ] = 'looking_in';
   > 
   > directories = fs.readdir ( here , (err, directories) => {
   >     answer[ 'retrieved_data' ] = directories;
   >     back.send ( 'Hey_you' , answer );
>
   > } );

still closes immediately

**Comment by Chhekur** [comment]
> > > You can use `IPC` to share information between `front` and `back` process.
> > 
> > 
> > I used that but in Mobile it immediately closes:
> > > // ------- send App Location to back
> > > let path = app.getPath('userData');
> > > front.send ( 'here' , path );
> > 
> > 
> > > back.on ( 'here'     , function (data) { const here = data;  } );
> > > answer = Object.assign ( {} , answer_template );
> > > answer[ 'stat' ] = 'looking_in';
> > > directories = fs.readdirSync ( here );
> > > answer[ 'retrieved_data' ] = directories;
> > > back.send ( 'Hey_you' , answer );
> 
> You have to read read operations inside the callback function because javascript is async or you can use promise

Did you write this whole thing inside the ipc callback

**Comment by szhatef** [comment]
> Did you write this whole thing inside the ipc callback

this part in front:

>// ------- send App Location to back
> let path = app.getPath('userData');
> front.send ( 'here' , path );

this part in back:

 >   answer = Object.assign ( {} , answer_template );
 >   answer[ 'stat' ] = 'looking_in';
 >   
 >   fs.readdir ( here , (err, directories ) => {
 > >     answer[ 'retrieved_data' ] = directories;
 > >      back.send ( 'Hey_you' , answer );
>
 >   } );

I changed `readdirSyc` to `readdir`, but still it closes

**Comment by Chhekur** [comment]
> > Did you write this whole thing inside the ipc callback
> 
> this part in front:
> 
> > // ------- send App Location to back
> > let path = app.getPath('userData');
> > front.send ( 'here' , path );
> 
> this part in back:
> 
> > back.on ( 'here'     , function (data) { const here = data;  } );
> > answer = Object.assign ( {} , answer_template );
> > answer[ 'stat' ] = 'looking_in';
> > fs.readdir ( here , (err, directories ) => {
> > > answer[ 'retrieved_data' ] = directories;
> > > back.send ( 'Hey_you' , answer );
> > 
> > 
> > } );
> 
> I changed `readdirSyc` to `readdir`, but still it closes

You have to write whole dependent code inside the back's callback.

Do you know how javascript works ?

**Comment by szhatef** [comment]
> > > Did you write this whole thing inside the ipc callback
> > 
> > 
> > this part in front:
> > > // ------- send App Location to back
> > > let path = app.getPath('userData');
> > > front.send ( 'here' , path );
> > 
> > 
> > this part in back:
> > > back.on ( 'here'     , function (data) { const here = data;  } );
> > > answer = Object.assign ( {} , answer_template );
> > > answer[ 'stat' ] = 'looking_in';
> > > fs.readdir ( here , (err, directories ) => {
> > > > answer[ 'retrieved_data' ] = directories;
> > > > back.send ( 'Hey_you' , answer );
> > > 
> > > 
> > > } );
> > 
> > 
> > I changed `readdirSyc` to `readdir`, but still it closes
> 
> You have to write whole dependent code inside the back's callback.
> 
> Do you know how javascript works ?

 it has been summarized here, it is a part of over 1500  lines of coeds,
this part will be triggered in appropriate time: (it is a tiny part of a function named looker, which will call in later, and if I set the `here` to `/sdcard/www/content` it works fine )

> > > answer = Object.assign ( {} , answer_template );
> > > answer[ 'stat' ] = 'looking_in';
> > > fs.readdir ( here , (err, directories ) => {
> > > > answer[ 'retrieved_data' ] = directories;
> > > > back.send ( 'Hey_you' , answer );

**Comment by Chhekur** [comment]
> > > > Did you write this whole thing inside the ipc callback
> > > 
> > > 
> > > this part in front:
> > > > // ------- send App Location to back
> > > > let path = app.getPath('userData');
> > > > front.send ( 'here' , path );
> > > 
> > > 
> > > this part in back:
> > > > back.on ( 'here'     , function (data) { const here = data;  } );
> > > > answer = Object.assign ( {} , answer_template );
> > > > answer[ 'stat' ] = 'looking_in';
> > > > fs.readdir ( here , (err, directories ) => {
> > > > > answer[ 'retrieved_data' ] = directories;
> > > > > back.send ( 'Hey_you' , answer );
> > > > 
> > > > 
> > > > } );
> > > 
> > > 
> > > I changed `readdirSyc` to `readdir`, but still it closes
> > 
> > 
> > You have to write whole dependent code inside the back's callback.
> > Do you know how javascript works ?
> 
> it has been summarized here, it is a part of over 1500 lines of coeds,
> this part will be triggered in appropriate time: (it is a tiny part of a function named looker, which will call in later, and if I set the `here` to `/sdcard/www/content` it works fine )
> 
> > > > answer = Object.assign ( {} , answer_template );
> > > > answer[ 'stat' ] = 'looking_in';
> > > > fs.readdir ( here , (err, directories ) => {
> > > > > answer[ 'retrieved_data' ] = directories;
> > > > > back.send ( 'Hey_you' , answer );

Yeah, I am not saying to write whole thung inside the callback but you have to write whole code which are dependent on `here` inside the callback

**Comment by szhatef** [comment]
> Yeah, I am not saying to write whole thung inside the callback but you have to write whole code which are dependent on `here` inside the callback

so do you mean this code : 
 > back.on ( 'here' , function (data) { const here = data; } );
will not set `here` globally?!

**Comment by Chhekur** [comment]
> > Yeah, I am not saying to write whole thung inside the callback but you have to write whole code which are dependent on `here` inside the callback
> 
> so do you mean this code :
> 
> > back.on ( 'here' , function (data) { const here = data; } );
> 
> will not set `here` globally?!

No, not at all because of async behaviour of javascript.

**Comment by szhatef** [comment]
> > > Yeah, I am not saying to write whole thung inside the callback but you have to write whole code which are dependent on `here` inside the callback
> > 
> > 
> > so do you mean this code :
> > > back.on ( 'here' , function (data) { const here = data; } );
> > 
> > 
> > will not set `here` globally?!
> 
> No, not at all because of async behaviour of javascript.

so HOw can I send it to back at the starting of App and store the location for entire Time and use it as other `const` vars?

**Comment by Chhekur** [comment]
Not possible to save the value of `here` because of js async behaviour.
I used the same concept in `sample story app`, you can check soruce for the reference.

**Comment by EmilDeGuerrero** [comment]
Hi its been a while nobady make a comment.

Please im trayng to read files im the back. but it does not work outside of appData folder.
can anybody please giveme me some info.
i added 

...
"permission": ["android.permission.INTERNET", "android.permission.WRITE_EXTERNAL_STORAGE", "android.permission.READ_EXTERNAL_STORAGE"],
...

in the package.json
without siccess.

note that if i run the app im the pc and in a virtual android machine i have it works, but in a fone it does not work outsidr of appData.


hope anybody read this and help.
