### ISSUE TITLE
Can I get the external storage path?

### ISSUE THREAD

**Issue by dev-huiya** [android-js/androidjs#66]
According to the api document, there seems to be no function to obtain an external storage path like Environment.getExternalStorageDirectory().

I want to support external storage in my app.

Is there any api or other way I didn't find?

**Comment by szhatef** [comment]
const path = require ( 'path' );
const fs = require ( 'fs' );
const root = '/sdcard';

    contents = fs.readdirSync ( root );
    directories = contents.filter ( function (file) {    
       
    } );

**Comment by danbulant** [comment]
@szhatef that doesn't always work, the /sdcard might not be present at all, or have a different name (mine has letters and numbers combination)

**Comment by szhatef** [comment]
> @szhatef that doesn't always work, the /sdcard might not be present at all, or have a different name (mine has letters and numbers combination)

use this one:

android.os.Environment.getExternalStorageDirectory().getAbsolutePath().toString();

**Comment by frabjous** [comment]
> use this one:
> 
> `const root = android.os.Environment.getExternalStorageDirectory().getAbsolutePath().toString();`
> 
> :)

Sorry if I'm being a clueless newb, but when I try that on back it tells me android is not defined. When I try it on front it tells me it can't read property Environment of null.
