### ISSUE TITLE
Hide top bar with app name

### ISSUE THREAD

**Issue by ChineseOuchie** [android-js/androidjs#72]
Can't find in the documentation about hiding the top bar when the app has launched. I'm talking about the bar where you can see your app in.

**Comment by ChineseOuchie** [comment]
NVM

```
"theme": {
	"fullScreen": true,
    "colorAccent": "#B9D154",
    "colorPrimary": "#B9D154",
    "colorPrimaryDark": "#B9D154"
  }
```

The "S" in fullscreen has to be in caps.

**Comment by AnteraTres** [comment]
But with the "fullScreen" option on the Theme section, you can't see the status bar with the hour, battery and notifications. Is there any option to be fullscreen but with that bar?

**Comment by ChineseOuchie** [comment]
Not sure, it might be better to start a new issue if your question.

Another option is to make your own status bar.
