### ISSUE TITLE
TypeError: Cannot read property 'resources' of undefined

### ISSUE THREAD

**Issue by atmoner** [android-js/androidjs#75]
Hello, I try to make the examples work but impossible!  
I have this recurring error:

```
atmo@atmo:~/Bureau/sample-app/helloworld$ androidjs b -f
Testing 'Theme Update' ...
webview: myapp
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
/usr/local/lib/node_modules/androidjs-builder/lib/update_theme.js:40
                    let thm = result.resources.style[6].item;
                                     ^

TypeError: Cannot read property 'resources' of undefined
    at /usr/local/lib/node_modules/androidjs-builder/lib/update_theme.js:40:38
    at Parser.<anonymous> (/usr/local/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:310:18)
    at Parser.emit (events.js:210:5)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:329:16)
    at Parser.parseString (/usr/local/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:5:59)
    at ReadFileContext.callback (/usr/local/lib/node_modules/androidjs-builder/lib/update_theme.js:36:24)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13)
```

I feel like he's trying to load an xml file that doesn't exist

**Comment by Chhekur** [comment]
Generate the new project with builder then it will work
`androidjs init`

**Comment by usernein** [comment]
Even with `androidjs init` i still get that error

**Comment by atmoner** [comment]
Hello @Chhekur 
Same as @usernein 

I have the impression that he cannot open an xml file! He needs to load xml?

**Comment by Chhekur** [comment]
Are you guys using latest version of `androidjs-builder` ?

**Comment by usernein** [comment]
@Chhekur yes, i'm using the version 2.0.3 of androidjs-builder
![](https://usernein.souunick.com/print1.jpg)

And when i tried to use `androidjs update` i got another error that i already saw before:
![](https://usernein.souunick.com/print2.jpg)

**Comment by Chhekur** [comment]
> @Chhekur yes, i'm using the version 2.0.3 of androidjs-builder
> ![](https://camo.githubusercontent.com/869c25792b695f98e1b6f47279682020567e6601/68747470733a2f2f757365726e65696e2e736f75756e69636b2e636f6d2f7072696e74312e6a7067)
> 
> And when i tried to use `androidjs update` i got another error that i already saw before:
> ![](https://camo.githubusercontent.com/c87a710cd36d3da6d364ae9af2e3b5d013763a19/68747470733a2f2f757365726e65696e2e736f75756e69636b2e636f6d2f7072696e74322e6a7067)

This error occurs because of slow internet connection. So you just need to repeatedly run the command until it works ; )

**Comment by usernein** [comment]
But it is a vps on Digital Ocean

**Comment by atmoner** [comment]
> This error occurs because of slow internet connection. So you just need to repeatedly run the command until it works ; )


I've been trying 50 times and it doesn't work.
And honestly, I don't think the problem comes from the connection!
I will try with another project, I give up with this one

**Comment by usernein** [comment]
@Chhekur the server has a stable and fast connection, it's a vps of Digital Ocean and wget shows about 25MB/s
The error keeps throwing even after multiple times

**Comment by Chhekur** [comment]
Delete the `theme` attribute from your app's `package.json` file.

**Comment by usernein** [comment]
@Chhekur same "total required" error
![](https://usernein.souunick.com/print3.jpg)

And `androidjs b -f` returns the same

**Comment by Chhekur** [comment]
> @Chhekur same "total required" error after removing the "theme" attribute
> ![](https://camo.githubusercontent.com/94669cf189f4addac20e1bde1535e6d1614d6c29/68747470733a2f2f757365726e65696e2e736f75756e69636b2e636f6d2f7072696e74332e6a7067)
> 
> And `androidjs b -f` returns the same

Try to build again,
This error occurs when it tries to download core from internet but got the payload of size 0.

So try again and make sure internet is working

**Comment by cesoun** [comment]
The only way around any of these errors for me was to elevate the permission with `sudo` otherwise the build would fail every time.

Might be worth checking if the user ran the command with elevated permissions. Assuming `-f` will always throw the `'total required'` error otherwise as well if not elevated as well.

**Comment by atmoner** [comment]
@cesoun Not really secure, never do this! You don't know what other packages will be installed ...
@Chhekur Regarding the departure problem, it is still not resolved !!

![atmo@atmo: ~-Bureau-nodeDroid-nodeDroid_177](https://user-images.githubusercontent.com/1071490/73087577-002a1180-3ed3-11ea-98cf-22430b24e970.png)
