### ISSUE TITLE
index.js:70 throw err

### ISSUE THREAD

**Issue by PassionPenguin** [android-js/androidjs#76]
/usr/local/lib/node_modules/androidjs-builder/node_modules/jsonfile/index.js:70
      throw err

after this command:
androidjs init

**Comment by Chhekur** [comment]
Can you please provide the full log of error ?

**Comment by Romans96** [comment]
It gives the same error also to me: here is the log
https://hastebin.com/ivimuyokof.coffeescript

And also renaming the folder, when i go compile the apk it gives error

**Comment by Chhekur** [comment]
> It gives the same error also to me: here is the log
> https://hastebin.com/ivimuyokof.coffeescript
> 
> And also renaming the folder, when i go compile the apk it gives error

We are implementing the builder from scratch so most of the existing problem will be fixed : )

**Comment by Chhekur** [comment]
Hey, we have release new version of `androidjs-builder@2.1.4`, which may solve all the existing problem.
So you can upgrade to the latest version `2.1.4` and enjoy.

Follow these instruction to upgrade `androidjs-builder` to latest

```bash
$ npm uninstall -g androidjs-builder
$ npm install -g androidjs-builder@2.1.4
```

Feel free to ask in case of any problem ; )

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)
