### ISSUE TITLE
Packaging error

### ISSUE THREAD

**Issue by Angshu1** [android-js/androidjs#77]
Hey so.. when i try to build the app with androidjs b or androidjs b -f which is [The Story app](https://github.com/android-js/sample-app/tree/master/story-app)

it says

copying user app done.
User data copied
skipped to copy core module !
Core Modules Copied !
reading  C:\Users\mm\Desktop\eead\dist\app-debug\AndroidManifest.xml
package name com.androidjs.mypkg
{ '$': { 'android:name': 'android.permission.INTERNET' } }
{
  '$': { 'android:name': 'android.permission.WRITE_EXTERNAL_STORAGE' }
}
{ '$': { 'android:name': 'android.permission.READ_EXTERNAL_STORAGE' } }
Done!
AndroidManifest updated!
changing app name C:\Users\mm\Desktop\eead\dist\app-debug\res\values\strings.xml
{ _: 'myapp', '$': { name: 'app_name' } }
App Name updated!
Icon updated!
Building...
(node:7584) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    'C:\\Users\\mm\\AppData\\Roaming\\npm\\node_modules\\androidjs-builder\\bin\\build_tools\\apktool.jar',
    'b',
    'C:\\Users\\mm\\Desktop\\eead\\dist\\app-debug',
    '-o',
    'C:\\Users\\mm\\Desktop\\eead\\dist\\app.apk'
  ]
}

any help will be appreciated

**Comment by Angshu1** [comment]
Fixed by twerking and messing around

**Comment by chongjh** [comment]
> 
> 
> Fixed by twerking and messing around

Hi, I'm having this problem too. Could you let me know how you fix it and what version of androidjs and androidjs-builder are you using?

**Comment by Chhekur** [comment]
> > Fixed by twerking and messing around
> 
> Hi, I'm having this problem too. Could you let me know how you fix it and what version of androidjs and androidjs-builder are you using?

You should have Java installed, this error is generating because of Java.
