### ISSUE TITLE
Geolocation error: User denied Geolocation with androidjs 2.0.2

### ISSUE THREAD

**Issue by mike06006** [android-js/androidjs#85]
Hi everyone! 
I can't find a solution for this Geolocation error when app is running on the phone (with location activated of course). The app never asks me the geolocation permission.
Here are the permissions I put in package.json:
"permission": [
    "android.permission.INTERNET",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION"
  ],
And this is the code in index.html for the geolocation (using leaflet.locatecontrol@0.70.0):
L.control.locate({position: 'topright'}).addTo(mymap);
On the laptop in local mode, the html is OK and the geolocation works perfectly after asking me the geolocation permission.
Someone knows how to fix it please? Is androidjs allows the geolocation or it is not possible yet?

**Comment by appsdevpk** [comment]
Same issue here

**Comment by Chhekur** [comment]
Actually we haven't implemented any `API` for `geolocation` yet.
But we'll definitely implement it ; )

**Comment by mike06006** [comment]
Thank you very much. You do a really good job!!

**Comment by Chhekur** [comment]
Hey guys,
we have implemented `Location API` in `Android JS @ 2.0.3`.
you guys can checkout the documentation for more information.
- First update your SDK
   ```bash
    $ androidjs update
   ```
- Update `Android JS` to `2.0.3`
   ```bash
    $ npm install androidjs@2.0.3
    ```
docs: https://android-js.github.io/docs/location_api.html

**Comment by Chhekur** [comment]
Sample app for Location API
https://github.com/android-js/sample-app/tree/master/location-api-example

**Comment by mike06006** [comment]
wonderfull job thank you!
