### ISSUE TITLE
Hold the datas load

### ISSUE THREAD

**Issue by Romans96** [android-js/androidjs#91]
**Describe the bug**
Hello! I would to handle the page load (the part that come from the front.on), in order to create a "progress bar, or a loading gif". I'm trying from days to do that but without any success, both with plain javascript or with jquery, it doesn't work because it handle the load of the index.html page without the datas that comes from the fron.on() methods.
So i tried also to promise the fron.on methods but without any success.
So if you have do something like a progres//loading, how did you handle with this framework? 
THak you

**Expected behavior**
Progressbar/gif image until it loads the content from the nodejs functions

**Desktop (please complete the following information):**
 - OS: windows10

**Comment by Chhekur** [comment]
you can actually put logic for disabling progress bar inside `front.on`, since it is a listener so it'll called once it'll get the data and will disable the progress ; )
