### ISSUE TITLE
Open links in external browser?

### ISSUE THREAD

**Issue by Romans96** [android-js/androidjs#93]
Hello! I would that the html links opens in an external browser, not internally at the app.
I tried with something like these:
adding the `target="_blank"` or the `target="_system"`, and also i added an attribute on the a tags like:
`window.open(this.href, '_system');`

But all of them doesn't work, they opens the link in an app. Did you have inserted something to handle this? THank you

**Comment by Chhekur** [comment]
Hey, we have fixed that, so you just need to update you `androidjs SDK` to latest one then you'll good to go.

In order to update `SDK` run the following command:
```bash
$ androidjs update
```
so now links with `target=_blank` will be opened in browser and normal links will be serve as before ; )

Feel free to ask in case of any problem ; )

**Comment by Romans96** [comment]
> Hey, we have fixed that, so you just need to update you `androidjs SDK` to latest one then you'll good to go.
> 
> In order to update `SDK` run the following command:
> 
> ```shell
> $ androidjs update
> ```
> 
> so now links with `target=_blank` will be opened in browser and normal links will be serve as before ; )
> 
> Feel free to ask in case of any problem ; )

I solved thank you (i needed to install sdk manually form github, androidjs update download, but not update in folder). But now it seems to works perfectly :) Thank you

**Comment by eliassr75** [comment]
Hi!!
how to update sdk manually? i not finded the folder....

**Comment by eliassr75** [comment]
my version is 2.2.0, but the function not running.....
