### ISSUE TITLE
Resources undefined.

### ISSUE THREAD

**Issue by Stanlyhalo** [android-js/androidjs#95]
**The Error**
When I get my project setup to try the first build, I get an error saying: "Cannot read property 'resources' of undefined"

**How To Reproduce**
1. Make the startup project from https://android-js.github.io/
2. Build

**Expected Behavior Of The Output**
It should build into a dist directory

**Screenshot Of Command Prompt**
![image](https://user-images.githubusercontent.com/36088749/76692025-03f22e80-660e-11ea-9575-e79e276bbbbf.png)

**Desktop:**
 - OS: Windows 10

**Comment by Chhekur** [comment]
Hey, we have release new version of `androidjs-builder@2.1.4`, which may solve all the existing problem.
So you can upgrade to the latest version `2.1.4` and enjoy.

Follow these instruction to upgrade `androidjs-builder` to latest

```bash
$ npm uninstall -g androidjs-builder
$ npm install -g androidjs-builder@2.1.4
```

Feel free to ask in case of any problem ; )

**Comment by Stanlyhalo** [comment]
Thank you, finally, and yes, I have one question, and it may be a simple solution, so it's not big for a new issue post, how do I remove the app title bar that shows up on the top with the name of my app?

**Comment by Stanlyhalo** [comment]
Nvm, found an issue on someone else's post about removing it, and it was just that I needed to set fullScreen to true, but thank you for the quick update on androidjs-builder.
