### ISSUE TITLE
Know if wifi/internet is actived?

### ISSUE THREAD

**Issue by Romans96** [android-js/androidjs#97]
Hello! I've seen on your docs that androidjs have the wifi api, microphone, toast, etc. How cna i use them?
In the Project i can't import other api except of the front and back (in fact opening it there is no libraries, like toast or wifi).

I would use the toast and more important, is there a way in order to check if internet is enabled or not? I see that wifi api permit to turn on/of but not to check if wifi/3g/4g are turned on.
Thank you

**Comment by Chhekur** [comment]
Hey, did you go through the documentation because there is properly documented how to use them.

all the `API's` are available inside `app` object in `front` process, which means in `views`

Feel free to ask in case of any problem ; )

**Comment by Romans96** [comment]
> Hey, did you go through the documentation because there is properly documented how to use them.
> 
> all the `API's` are available inside `app` object in `front` process, which means in `views`
> 
> Feel free to ask in case of any problem ; )

Hello! Yes thank you i've just tested it with a toast and it works, but i can't find a way to check if internet is active. because it exists a method for check if wifi is enabled, but not for the 3g/4g or in general if "there is internet".
Thank you

**Comment by Chhekur** [comment]
> > Hey, did you go through the documentation because there is properly documented how to use them.
> > all the `API's` are available inside `app` object in `front` process, which means in `views`
> > Feel free to ask in case of any problem ; )
> 
> Hello! Yes thank you i've just tested it with a toast and it works, but i can't find a way to check if internet is active. because it exists a method for check if wifi is enabled, but not for the 3g/4g or in general if "there is internet".
> Thank you

Yeah, we are working on the same `API`, you will get it as soon ; )

**Comment by Chhekur** [comment]
Hey, We have implemented `Mobile Data API` in `androidjs@2.0.4`.
You just need to update `SDK` to latest and `androidjs` to latest

Feel free to ask in case of any error ; )
