### ISSUE TITLE
Non zero exit code

### ISSUE THREAD

**Issue by quartze** [android-js/androidjs#99]
I had a some errors with create apk. I use this commands:
> androidjs init
app name: alexa
> cd alexa
> androidjs b -f

and in console i got:

```
copying assets ...
updating app name...
updating theme ...
Using SDK: 2.0.5
Building Apk ...
non zero exit code: failed to build apk
```

@update:
When i trying to build something from GIT repository (e.g. chat-app) i literally got the same error:
```
building ...3 : [blocks]
non zero exit code: failed to build apk
```

**Comment by DeveshPankaj** [comment]
Make sure you have installed **Java Version >= [1.8.0](https://filehippo.com/download_jre_64/)** in your system.

If you have installed a proper version, then retry after updating the ``Androidjs-SDK`` 
use this command to update:
```bash
$ androidjs update
```
---
OR
```sh
$ cd ~
$ rm .androidjs
$ npm uninstall androidjs-builder -g
$ npm install androidjs-builder -g
```
